# Generated by Django 4.2.13 on 2024-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardid', models.CharField(max_length=50)),
                ('import_date', models.DateTimeField()),
                ('deactivate_date', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('lastaccess', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('macID', models.CharField(max_length=50)),
                ('lastseen', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('doorlocked', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cardid', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
