# Generated by Django 4.2.13 on 2024-05-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='reader',
            field=models.CharField(default='In Reader', max_length=30),
        ),
    ]
