# Generated by Django 4.2.13 on 2024-05-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 57, 55, 291869)),
        ),
    ]
