# Generated by Django 4.2.13 on 2024-05-28 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0002_alter_door_lastaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImoprtCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 51, 47, 886264)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 51, 47, 886264)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
