# Generated by Django 4.2.13 on 2024-05-28 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0003_imoprtcard_alter_door_lastaccess_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imoprtcard',
            old_name='file',
            new_name='CardID',
        ),
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 53, 24, 952299)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 53, 24, 952299)),
        ),
    ]
