# Generated by Django 4.2.13 on 2024-05-27 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0003_department_alter_door_lastaccess_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 15, 51, 0, 371771)),
        ),
    ]
