# Generated by Django 4.2.13 on 2024-05-29 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0004_rename_file_imoprtcard_cardid_alter_door_lastaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 10, 26, 47, 934918)),
        ),
        migrations.AlterField(
            model_name='imoprtcard',
            name='CardID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reader',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 10, 26, 47, 934918)),
        ),
    ]
