# Generated by Django 4.2.13 on 2024-05-30 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller1', '0005_alter_door_lastaccess_alter_imoprtcard_cardid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='door',
            name='lastaccess',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 47, 16, 274615)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 47, 16, 274615)),
        ),
    ]
